export default {
  MY_PASSENGERS_DATA: 'MY_PASSENGERS_DATA',
  MY_PASSENGERS_CARD_ID: 'MY_PASSENGERS_CARD_ID',
  DROPOFF_PICKUP_CONFIRMATION: 'DROPOFF_PICKUP_CONFIRMATION',
  MY_PASSENGERS_CARD_ID_PICKUP: 'MY_PASSENGERS_CARD_ID_PICKUP',
};
