export default {
  INDEX_ROUTE: 'INDEX_ROUTE',
  SEARCH_PARAM: 'SEARCH_PARAM',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  PASSENGERS_DATA: 'PASSENGERS_DATA',
  PASSENGERS_CARD_ID: 'PASSENGERS_CARD_ID',
  PICKUP_PASSENGER_CARD_ID: 'PICKUP_PASSENGER_CARD_ID',
  ADD_TO_MY_PASSENGERS_SUCCESS: 'ADD_TO_MY_PASSENGERS_SUCCESS',
  UNASSIGNED_PICKUP_PASSENGERS: 'UNASSIGNED_PICKUP_PASSENGERS',
  UNASSIGNED_DROP_OFF_PASSENGERS: 'UNASSIGNED_DROP_OFF_PASSENGERS',
};
