export default {
  PASSENGER_INFO: 'PASSENGER_INFO',
  ADD_PASSENGER_DATA: 'ADD_PASSENGER_DATA',
  NEW_ADDRESS_FROM_GOOGLE: 'NEW_ADDRESS_FROM_GOOGLE',
  TOGGLE_CONFIRMATION_POPUP: 'TOGGLE_CONFIRMATION_POPUP',
  TOGGLE_GOOGLE_PLACES_INPUT: 'TOGGLE_GOOGLE_PLACES_INPUT',
  TOGGLE_ALL_PASSENGERS_MODAL: 'TOGGLE_ALL_PASSENGERS_MODAL',
  TOGGLE_EDIT_PASSENGER_MODAL: 'TOGGLE_EDIT_PASSENGER_MODAL',
  TOGGLE_ADD_PASSENGER_MODAL: 'TOGGLE_ADD_PASSENGER_MODAL',
  CANCEL_PASSENGER_EDIT_ACTION: 'CANCEL_PASSENGER_EDIT_ACTION',
};
